spring.application.name=backend
server.port=8080

minio.url=http://127.0.0.1:9000
minio.access-key=local
minio.secret-key=Avi@123456789
minio.bucket=user-files
spring.docker.compose.enabled=false
logging.level.io.minio=DEBUG

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true