spring.application.name=backend
server.port=8080

# MinIO
minio.url=http://127.0.0.1:9000
minio.access-key=local
minio.secret-key=Avi@123456789
minio.bucket=user-files

spring.docker.compose.enabled=false
logging.level.io.minio=DEBUG

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-billowing-waterfall-az82n0js-pooler.c-3.ap-southeast-1.aws.neon.tech/vaulticBackend?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fq79jKrewZvO
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true